### ISSUE TITLE
Criar input de texto padrão reutilizavel. 

### ISSUE THREAD

**Issue by guilhermeSDB** [Uno-Online/uno-frontend#4]
**Descrição:**
Criar entrada de texto(input text) reutilizavel padrão para textos.

**Regras:**
* Deve conter um Label
* Deve conter placeholder.
* Deve conter funcionalidade para deixar o campo obrigatório ou não.
* Deve conter um * (astericos) em vermelho do lado do Label caso seja obrigatório.
* Todo o código deve ser inglês exceto Placeholders.

**Observações:**
* Não se preocupe tanto com o estilo, e sim funcionalidade, não temos estilos definidos ainda.
* Não se esqueça de criar uma branch nova para sua tarefa.

**Exemplo:**
O exemplo é meramente ilustrativo, faça o que esta descrito nas Regras.

![image](https://user-images.githubusercontent.com/66280834/226192718-99e82072-c48a-40bd-a2e0-6eb45212541f.png)

**Comment by EduNunesGithub** [comment]
Irei começar a fazer essa tarefa

**Comment by guilhermeSDB** [comment]
Ficou ótimo!
